name: build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci

      - env:
          V: ${{ secrets.CONFIG_VALUES_TS }}
        run: echo "${V}" > functions/src/config.values.ts

      - env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: ${{ secrets.FIREBASE_PROJECT }}
        run: npm run deploy -- -P ${FIREBASE_PROJECT}
